#!/bin/bash

ANDROID_STUDIO_HOME=/opt/android-studio
export ANDROID_SDK_ROOT=/home/joachim/Android/Sdk

export NODE_OPTIONS=--openssl-legacy-provider
export JDK_HOME=$ANDROID_STUDIO_HOME/jbr/
export JAVA_HOME=$ANDROID_STUDIO_HOME/jbr/
export PATH=$ANDROID_STUDIO_HOME/jbr/bin:$PATH

npx react-native run-android
npx react-native start
